### ISSUE TITLE
project doesn't run with ember v1.13.1

### ISSUE THREAD

**Issue by socketwiz** [balinterdi/rock-and-roll#7]
The project doesn't seem to run with ember v1.13.1. All I did was clone the project and try to run ember server.

```
RICKYNELSON ➜  dev  git clone https://github.com/balinterdi/rock-and-roll.git
Cloning into 'rock-and-roll'...
remote: Counting objects: 600, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 600 (delta 2), reused 0 (delta 0), pack-reused 594
Receiving objects: 100% (600/600), 977.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (264/264), done.
Checking connectivity... done.
RICKYNELSON ➜  dev  cd rock-and-roll
RICKYNELSON ➜  rock-and-roll git:(master) ember server
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at AddonDiscovery.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:107:24)
    at Array.map (native)
    at AddonDiscovery.discoverFromDependencies (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:97:68)
    at AddonDiscovery.discoverProjectAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:45:31)
    at Project.discoverAddons (/usr/local/lib/node_modules/ember-cli/lib/models/project.js:317:40)
    at Project.initializeAddons (/usr/local/lib/node_modules/ember-cli/lib/models/project.js:336:8)
    at Project.eachAddonCommand (/usr/local/lib/node_modules/ember-cli/lib/models/project.js:389:10)
    at module.exports (/usr/local/lib/node_modules/ember-cli/lib/cli/lookup-command.js:34:13)
    at CLI.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:35:26)
RICKYNELSON ➜  dev  cd ..
RICKYNELSON ➜  dev  ember --version
version: 1.13.1
node: 0.12.5
npm: 2.12.1
```

**Comment by dondanhill** [comment]
try npm install && bower install

**Comment by balinterdi** [comment]
What @dondanhill says. If you ran `git clone`, that just checks out a copy of the repo, you still need to install the "backend" and frontend dependencies, which is what `npm install && bower install` does.

**Comment by socketwiz** [comment]
Wow, I can't believe I missed those steps, thanks!
